<?php

$elements = <<<EOT
[main 52f1c72] wip #12
 678 files changed, 23837 insertions(+), 221 deletions(-)
 create mode 100644 0_proto/4_shader_tests/32_detection_files/1_xr-for-non-humans/above-and-below-aquateque-digital-film-itsnicethat-03.webp
 create mode 100644 0_proto/4_shader_tests/32_detection_files/1_xr-for-non-humans/above-and-below-aquateque-digital-film-itsnicethat-06.webp
 create mode 100644 0_proto/4_shader_tests/32_detection_files/1_xr-for-non-humans/above-and-below-aquateque-digital-film-itsnicethat-10.webp
 create mode 100644 0_proto/4_shader_tests/32_detection_files/1_xr-for-non-humans/above-and-belowdigitalatmosphere_outdoor_03-1536x864.jpg
 create mode 100644 0_proto/4_shader_tests/32_detection_files/1_xr-for-non-humans/above-and-belowdigitalatmosphere_outdoor_06.jpg
 create mode 100644 0_proto/4_shader_tests/32_detection_files/1_xr-for-non-humans/results.json
 create mode 100644 0_proto/4_shader_tests/32_detection_files/2_biofabricated-soft-robots-and-inflatables/event.txt
 create mode 100644 0_proto/4_shader_tests/32_detection_files/2_biofabricated-soft-robots-and-inflatables/marisa-latest-2.jpg
 create mode 100644 0_proto/4_shader_tests/32_detection_files/2_biofabricated-soft-robots-and-inflatables/marisa-latest-2.jpg.txt
 create mode 100644 0_proto/4_shader_tests/32_detection_files/2_biofabricated-soft-robots-and-inflatables/marisa-satsia.png
 create mode 100644 0_proto/4_shader_tests/32_detection_files/2_biofabricated-soft-robots-and-inflatables/marisa-satsia.png.txt
 create mode 100644 0_proto/4_shader_tests/32_detection_files/2_biofabricated-soft-robots-and-inflatables/marisa-satsia141887338_2914462238791486_8870051184732449202_n.jpg
 create mode 100644 0_proto/4_shader_tests/32_detection_files/2_biofabricated-soft-robots-and-inflatables/marisa-satsia141887338_2914462238791486_8870051184732449202_n.jpg.txt
 create mode 100644 0_proto/4_shader_tests/32_detection_files/2_biofabricated-soft-robots-and-inflatables/marisa1-1920x1280.jpg
 create mode 100644 0_proto/4_shader_tests/32_detection_files/2_biofabricated-soft-robots-and-inflatables/marisa1-1920x1280.jpg.txt
 create mode 100644 assets/images/icon-console-reportinput.svg
 create mode 100644 assets/images/icon-console-textinput.svg
 create mode 100644 assets/lib/highlight/DIGESTS.md
 create mode 100644 assets/lib/highlight/LICENSE
 create mode 100644 assets/lib/highlight/README.md
 create mode 100644 assets/lib/highlight/es/core.js
 create mode 100644 assets/lib/highlight/es/core.min.js
 create mode 100644 assets/lib/highlight/es/highlight.js
 create mode 100644 assets/lib/highlight/es/languages/1c.min.js
 create mode 100644 assets/lib/highlight/es/languages/abnf.min.js
 create mode 100644 assets/lib/highlight/es/languages/accesslog.min.js
 create mode 100644 assets/lib/highlight/es/languages/actionscript.min.js
 create mode 100644 assets/lib/highlight/es/languages/ada.min.js
 create mode 100644 assets/lib/highlight/es/languages/angelscript.min.js
 create mode 100644 assets/lib/highlight/es/languages/apache.min.js
 create mode 100644 assets/lib/highlight/es/languages/applescript.min.js
 create mode 100644 assets/lib/highlight/es/languages/arcade.min.js
 create mode 100644 assets/lib/highlight/es/languages/arduino.min.js
 create mode 100644 assets/lib/highlight/es/languages/armasm.min.js
 create mode 100644 assets/lib/highlight/es/languages/asciidoc.min.js
 create mode 100644 assets/lib/highlight/es/languages/aspectj.min.js
 create mode 100644 assets/lib/highlight/es/languages/autohotkey.min.js
 create mode 100644 assets/lib/highlight/es/languages/autoit.min.js
 create mode 100644 assets/lib/highlight/es/languages/avrasm.min.js
 create mode 100644 assets/lib/highlight/es/languages/awk.min.js
 create mode 100644 assets/lib/highlight/es/languages/axapta.min.js
 create mode 100644 assets/lib/highlight/es/languages/bash.min.js
 create mode 100644 assets/lib/highlight/es/languages/basic.min.js
 create mode 100644 assets/lib/highlight/es/languages/bnf.min.js
 create mode 100644 assets/lib/highlight/es/languages/brainfuck.min.js
 create mode 100644 assets/lib/highlight/es/languages/c.min.js
 create mode 100644 assets/lib/highlight/es/languages/cal.min.js
 create mode 100644 assets/lib/highlight/es/languages/capnproto.min.js
 create mode 100644 assets/lib/highlight/es/languages/ceylon.min.js
 create mode 100644 assets/lib/highlight/es/languages/clean.min.js
 create mode 100644 assets/lib/highlight/es/languages/clojure-repl.min.js
 create mode 100644 assets/lib/highlight/es/languages/clojure.min.js
 create mode 100644 assets/lib/highlight/es/languages/cmake.min.js
 create mode 100644 assets/lib/highlight/es/languages/coffeescript.min.js
 create mode 100644 assets/lib/highlight/es/languages/coq.min.js
 create mode 100644 assets/lib/highlight/es/languages/cos.min.js
 create mode 100644 assets/lib/highlight/es/languages/cpp.min.js
 create mode 100644 assets/lib/highlight/es/languages/crmsh.min.js
 create mode 100644 assets/lib/highlight/es/languages/crystal.min.js
 create mode 100644 assets/lib/highlight/es/languages/csharp.min.js
 create mode 100644 assets/lib/highlight/es/languages/csp.min.js
 create mode 100644 assets/lib/highlight/es/languages/css.min.js
 create mode 100644 assets/lib/highlight/es/languages/d.min.js
 create mode 100644 assets/lib/highlight/es/languages/dart.min.js
 create mode 100644 assets/lib/highlight/es/languages/delphi.min.js
 create mode 100644 assets/lib/highlight/es/languages/diff.min.js
 create mode 100644 assets/lib/highlight/es/languages/django.min.js
 create mode 100644 assets/lib/highlight/es/languages/dns.min.js
 create mode 100644 assets/lib/highlight/es/languages/dockerfile.min.js
 create mode 100644 assets/lib/highlight/es/languages/dos.min.js
 create mode 100644 assets/lib/highlight/es/languages/dsconfig.min.js
 create mode 100644 assets/lib/highlight/es/languages/dts.min.js
 create mode 100644 assets/lib/highlight/es/languages/dust.min.js
 create mode 100644 assets/lib/highlight/es/languages/ebnf.min.js
 create mode 100644 assets/lib/highlight/es/languages/elixir.min.js
 create mode 100644 assets/lib/highlight/es/languages/elm.min.js
 create mode 100644 assets/lib/highlight/es/languages/erb.min.js
 create mode 100644 assets/lib/highlight/es/languages/erlang-repl.min.js
 create mode 100644 assets/lib/highlight/es/languages/erlang.min.js
 create mode 100644 assets/lib/highlight/es/languages/excel.min.js
 create mode 100644 assets/lib/highlight/es/languages/fix.min.js
 create mode 100644 assets/lib/highlight/es/languages/flix.min.js
 create mode 100644 assets/lib/highlight/es/languages/fortran.min.js
 create mode 100644 assets/lib/highlight/es/languages/fsharp.min.js
 create mode 100644 assets/lib/highlight/es/languages/gams.min.js
 create mode 100644 assets/lib/highlight/es/languages/gauss.min.js
 create mode 100644 assets/lib/highlight/es/languages/gcode.min.js
 create mode 100644 assets/lib/highlight/es/languages/gherkin.min.js
 create mode 100644 assets/lib/highlight/es/languages/glsl.min.js
 create mode 100644 assets/lib/highlight/es/languages/gml.min.js
 create mode 100644 assets/lib/highlight/es/languages/go.min.js
 create mode 100644 assets/lib/highlight/es/languages/golo.min.js
 create mode 100644 assets/lib/highlight/es/languages/gradle.min.js
 create mode 100644 assets/lib/highlight/es/languages/graphql.min.js
 create mode 100644 assets/lib/highlight/es/languages/groovy.min.js
 create mode 100644 assets/lib/highlight/es/languages/haml.min.js
 create mode 100644 assets/lib/highlight/es/languages/handlebars.min.js
 create mode 100644 assets/lib/highlight/es/languages/haskell.min.js
 create mode 100644 assets/lib/highlight/es/languages/haxe.min.js
 create mode 100644 assets/lib/highlight/es/languages/hsp.min.js
 create mode 100644 assets/lib/highlight/es/languages/http.min.js
 create mode 100644 assets/lib/highlight/es/languages/hy.min.js
 create mode 100644 assets/lib/highlight/es/languages/inform7.min.js
 create mode 100644 assets/lib/highlight/es/languages/ini.min.js
 create mode 100644 assets/lib/highlight/es/languages/irpf90.min.js
 create mode 100644 assets/lib/highlight/es/languages/isbl.min.js
 create mode 100644 assets/lib/highlight/es/languages/java.min.js
 create mode 100644 assets/lib/highlight/es/languages/javascript.min.js
 create mode 100644 assets/lib/highlight/es/languages/jboss-cli.min.js
 create mode 100644 assets/lib/highlight/es/languages/json.min.js
 create mode 100644 assets/lib/highlight/es/languages/julia-repl.min.js
 create mode 100644 assets/lib/highlight/es/languages/julia.min.js
 create mode 100644 assets/lib/highlight/es/languages/kotlin.min.js
 create mode 100644 assets/lib/highlight/es/languages/lasso.min.js
 create mode 100644 assets/lib/highlight/es/languages/latex.min.js
 create mode 100644 assets/lib/highlight/es/languages/ldif.min.js
 create mode 100644 assets/lib/highlight/es/languages/leaf.min.js
 create mode 100644 assets/lib/highlight/es/languages/less.min.js
 create mode 100644 assets/lib/highlight/es/languages/lisp.min.js
 create mode 100644 assets/lib/highlight/es/languages/livecodeserver.min.js
 create mode 100644 assets/lib/highlight/es/languages/livescript.min.js
 create mode 100644 assets/lib/highlight/es/languages/llvm.min.js
 create mode 100644 assets/lib/highlight/es/languages/lsl.min.js
 create mode 100644 assets/lib/highlight/es/languages/lua.min.js
 create mode 100644 assets/lib/highlight/es/languages/makefile.min.js
 create mode 100644 assets/lib/highlight/es/languages/markdown.min.js
 create mode 100644 assets/lib/highlight/es/languages/mathematica.min.js
 create mode 100644 assets/lib/highlight/es/languages/matlab.min.js
 create mode 100644 assets/lib/highlight/es/languages/maxima.min.js
 create mode 100644 assets/lib/highlight/es/languages/mel.min.js
 create mode 100644 assets/lib/highlight/es/languages/mercury.min.js
 create mode 100644 assets/lib/highlight/es/languages/mipsasm.min.js
 create mode 100644 assets/lib/highlight/es/languages/mizar.min.js
 create mode 100644 assets/lib/highlight/es/languages/mojolicious.min.js
 create mode 100644 assets/lib/highlight/es/languages/monkey.min.js
 create mode 100644 assets/lib/highlight/es/languages/moonscript.min.js
 create mode 100644 assets/lib/highlight/es/languages/n1ql.min.js
 create mode 100644 assets/lib/highlight/es/languages/nestedtext.min.js
 create mode 100644 assets/lib/highlight/es/languages/nginx.min.js
 create mode 100644 assets/lib/highlight/es/languages/nim.min.js
 create mode 100644 assets/lib/highlight/es/languages/nix.min.js
 create mode 100644 assets/lib/highlight/es/languages/node-repl.min.js
 create mode 100644 assets/lib/highlight/es/languages/nsis.min.js
 create mode 100644 assets/lib/highlight/es/languages/objectivec.min.js
 create mode 100644 assets/lib/highlight/es/languages/ocaml.min.js
 create mode 100644 assets/lib/highlight/es/languages/openscad.min.js
 create mode 100644 assets/lib/highlight/es/languages/oxygene.min.js
 create mode 100644 assets/lib/highlight/es/languages/parser3.min.js
 create mode 100644 assets/lib/highlight/es/languages/perl.min.js
 create mode 100644 assets/lib/highlight/es/languages/pf.min.js
 create mode 100644 assets/lib/highlight/es/languages/pgsql.min.js
 create mode 100644 assets/lib/highlight/es/languages/php-template.min.js
 create mode 100644 assets/lib/highlight/es/languages/php.min.js
 create mode 100644 assets/lib/highlight/es/languages/plaintext.min.js
 create mode 100644 assets/lib/highlight/es/languages/pony.min.js
 create mode 100644 assets/lib/highlight/es/languages/powershell.min.js
 create mode 100644 assets/lib/highlight/es/languages/processing.min.js
 create mode 100644 assets/lib/highlight/es/languages/profile.min.js
 create mode 100644 assets/lib/highlight/es/languages/prolog.min.js
 create mode 100644 assets/lib/highlight/es/languages/properties.min.js
 create mode 100644 assets/lib/highlight/es/languages/protobuf.min.js
 create mode 100644 assets/lib/highlight/es/languages/puppet.min.js
 create mode 100644 assets/lib/highlight/es/languages/purebasic.min.js
 create mode 100644 assets/lib/highlight/es/languages/python-repl.min.js
 create mode 100644 assets/lib/highlight/es/languages/python.min.js
 create mode 100644 assets/lib/highlight/es/languages/q.min.js
 create mode 100644 assets/lib/highlight/es/languages/qml.min.js
 create mode 100644 assets/lib/highlight/es/languages/r.min.js
 create mode 100644 assets/lib/highlight/es/languages/reasonml.min.js
 create mode 100644 assets/lib/highlight/es/languages/rib.min.js
 create mode 100644 assets/lib/highlight/es/languages/roboconf.min.js
 create mode 100644 assets/lib/highlight/es/languages/routeros.min.js
 create mode 100644 assets/lib/highlight/es/languages/rsl.min.js
 create mode 100644 assets/lib/highlight/es/languages/ruby.min.js
 create mode 100644 assets/lib/highlight/es/languages/ruleslanguage.min.js
 create mode 100644 assets/lib/highlight/es/languages/rust.min.js
 create mode 100644 assets/lib/highlight/es/languages/sas.min.js
 create mode 100644 assets/lib/highlight/es/languages/scala.min.js
 create mode 100644 assets/lib/highlight/es/languages/scheme.min.js
 create mode 100644 assets/lib/highlight/es/languages/scilab.min.js
 create mode 100644 assets/lib/highlight/es/languages/scss.min.js
 create mode 100644 assets/lib/highlight/es/languages/shell.min.js
 create mode 100644 assets/lib/highlight/es/languages/smali.min.js
 create mode 100644 assets/lib/highlight/es/languages/smalltalk.min.js
 create mode 100644 assets/lib/highlight/es/languages/sml.min.js
 create mode 100644 assets/lib/highlight/es/languages/sqf.min.js
 create mode 100644 assets/lib/highlight/es/languages/sql.min.js
 create mode 100644 assets/lib/highlight/es/languages/stan.min.js
 create mode 100644 assets/lib/highlight/es/languages/stata.min.js
 create mode 100644 assets/lib/highlight/es/languages/step21.min.js
 create mode 100644 assets/lib/highlight/es/languages/stylus.min.js
 create mode 100644 assets/lib/highlight/es/languages/subunit.min.js
 create mode 100644 assets/lib/highlight/es/languages/swift.min.js
 create mode 100644 assets/lib/highlight/es/languages/taggerscript.min.js
 create mode 100644 assets/lib/highlight/es/languages/tap.min.js
 create mode 100644 assets/lib/highlight/es/languages/tcl.min.js
 create mode 100644 assets/lib/highlight/es/languages/thrift.min.js
 create mode 100644 assets/lib/highlight/es/languages/tp.min.js
 create mode 100644 assets/lib/highlight/es/languages/twig.min.js
 create mode 100644 assets/lib/highlight/es/languages/typescript.min.js
 create mode 100644 assets/lib/highlight/es/languages/vala.min.js
 create mode 100644 assets/lib/highlight/es/languages/vbnet.min.js
 create mode 100644 assets/lib/highlight/es/languages/vbscript-html.min.js
 create mode 100644 assets/lib/highlight/es/languages/vbscript.min.js
 create mode 100644 assets/lib/highlight/es/languages/verilog.min.js
 create mode 100644 assets/lib/highlight/es/languages/vhdl.min.js
 create mode 100644 assets/lib/highlight/es/languages/vim.min.js
 create mode 100644 assets/lib/highlight/es/languages/wasm.min.js
 create mode 100644 assets/lib/highlight/es/languages/wren.min.js
 create mode 100644 assets/lib/highlight/es/languages/x86asm.min.js
 create mode 100644 assets/lib/highlight/es/languages/xl.min.js
 create mode 100644 assets/lib/highlight/es/languages/xml.min.js
 create mode 100644 assets/lib/highlight/es/languages/xquery.min.js
 create mode 100644 assets/lib/highlight/es/languages/yaml.min.js
 create mode 100644 assets/lib/highlight/es/languages/zephir.min.js
 create mode 100644 assets/lib/highlight/es/package.json
 create mode 100644 assets/lib/highlight/highlight.js
 create mode 100644 assets/lib/highlight/highlight.min.js
 create mode 100644 assets/lib/highlight/languages/1c.min.js
 create mode 100644 assets/lib/highlight/languages/abnf.min.js
 create mode 100644 assets/lib/highlight/languages/accesslog.min.js
 create mode 100644 assets/lib/highlight/languages/actionscript.min.js
 create mode 100644 assets/lib/highlight/languages/ada.min.js
 create mode 100644 assets/lib/highlight/languages/angelscript.min.js
 create mode 100644 assets/lib/highlight/languages/apache.min.js
 create mode 100644 assets/lib/highlight/languages/applescript.min.js
 create mode 100644 assets/lib/highlight/languages/arcade.min.js
 create mode 100644 assets/lib/highlight/languages/arduino.min.js
 create mode 100644 assets/lib/highlight/languages/armasm.min.js
 create mode 100644 assets/lib/highlight/languages/asciidoc.min.js
 create mode 100644 assets/lib/highlight/languages/aspectj.min.js
 create mode 100644 assets/lib/highlight/languages/autohotkey.min.js
 create mode 100644 assets/lib/highlight/languages/autoit.min.js
 create mode 100644 assets/lib/highlight/languages/avrasm.min.js
 create mode 100644 assets/lib/highlight/languages/awk.min.js
 create mode 100644 assets/lib/highlight/languages/axapta.min.js
 create mode 100644 assets/lib/highlight/languages/bash.min.js
 create mode 100644 assets/lib/highlight/languages/basic.min.js
 create mode 100644 assets/lib/highlight/languages/bnf.min.js
 create mode 100644 assets/lib/highlight/languages/brainfuck.min.js
 create mode 100644 assets/lib/highlight/languages/c.min.js
 create mode 100644 assets/lib/highlight/languages/cal.min.js
 create mode 100644 assets/lib/highlight/languages/capnproto.min.js
 create mode 100644 assets/lib/highlight/languages/ceylon.min.js
 create mode 100644 assets/lib/highlight/languages/clean.min.js
 create mode 100644 assets/lib/highlight/languages/clojure-repl.min.js
 create mode 100644 assets/lib/highlight/languages/clojure.min.js
 create mode 100644 assets/lib/highlight/languages/cmake.min.js
 create mode 100644 assets/lib/highlight/languages/coffeescript.min.js
 create mode 100644 assets/lib/highlight/languages/coq.min.js
 create mode 100644 assets/lib/highlight/languages/cos.min.js
 create mode 100644 assets/lib/highlight/languages/cpp.min.js
 create mode 100644 assets/lib/highlight/languages/crmsh.min.js
 create mode 100644 assets/lib/highlight/languages/crystal.min.js
 create mode 100644 assets/lib/highlight/languages/csharp.min.js
 create mode 100644 assets/lib/highlight/languages/csp.min.js
 create mode 100644 assets/lib/highlight/languages/css.min.js
 create mode 100644 assets/lib/highlight/languages/d.min.js
 create mode 100644 assets/lib/highlight/languages/dart.min.js
 create mode 100644 assets/lib/highlight/languages/delphi.min.js
 create mode 100644 assets/lib/highlight/languages/diff.min.js
 create mode 100644 assets/lib/highlight/languages/django.min.js
 create mode 100644 assets/lib/highlight/languages/dns.min.js
 create mode 100644 assets/lib/highlight/languages/dockerfile.min.js
 create mode 100644 assets/lib/highlight/languages/dos.min.js
 create mode 100644 assets/lib/highlight/languages/dsconfig.min.js
 create mode 100644 assets/lib/highlight/languages/dts.min.js
 create mode 100644 assets/lib/highlight/languages/dust.min.js
 create mode 100644 assets/lib/highlight/languages/ebnf.min.js
 create mode 100644 assets/lib/highlight/languages/elixir.min.js
 create mode 100644 assets/lib/highlight/languages/elm.min.js
 create mode 100644 assets/lib/highlight/languages/erb.min.js
 create mode 100644 assets/lib/highlight/languages/erlang-repl.min.js
 create mode 100644 assets/lib/highlight/languages/erlang.min.js
 create mode 100644 assets/lib/highlight/languages/excel.min.js
 create mode 100644 assets/lib/highlight/languages/fix.min.js
 create mode 100644 assets/lib/highlight/languages/flix.min.js
 create mode 100644 assets/lib/highlight/languages/fortran.min.js
 create mode 100644 assets/lib/highlight/languages/fsharp.min.js
 create mode 100644 assets/lib/highlight/languages/gams.min.js
 create mode 100644 assets/lib/highlight/languages/gauss.min.js
 create mode 100644 assets/lib/highlight/languages/gcode.min.js
 create mode 100644 assets/lib/highlight/languages/gherkin.min.js
 create mode 100644 assets/lib/highlight/languages/glsl.min.js
 create mode 100644 assets/lib/highlight/languages/gml.min.js
 create mode 100644 assets/lib/highlight/languages/go.min.js
 create mode 100644 assets/lib/highlight/languages/golo.min.js
 create mode 100644 assets/lib/highlight/languages/gradle.min.js
 create mode 100644 assets/lib/highlight/languages/graphql.min.js
 create mode 100644 assets/lib/highlight/languages/groovy.min.js
 create mode 100644 assets/lib/highlight/languages/haml.min.js
 create mode 100644 assets/lib/highlight/languages/handlebars.min.js
 create mode 100644 assets/lib/highlight/languages/haskell.min.js
 create mode 100644 assets/lib/highlight/languages/haxe.min.js
 create mode 100644 assets/lib/highlight/languages/hsp.min.js
 create mode 100644 assets/lib/highlight/languages/http.min.js
 create mode 100644 assets/lib/highlight/languages/hy.min.js
 create mode 100644 assets/lib/highlight/languages/inform7.min.js
 create mode 100644 assets/lib/highlight/languages/ini.min.js
 create mode 100644 assets/lib/highlight/languages/irpf90.min.js
 create mode 100644 assets/lib/highlight/languages/isbl.min.js
 create mode 100644 assets/lib/highlight/languages/java.min.js
 create mode 100644 assets/lib/highlight/languages/javascript.min.js
 create mode 100644 assets/lib/highlight/languages/jboss-cli.min.js
 create mode 100644 assets/lib/highlight/languages/json.min.js
 create mode 100644 assets/lib/highlight/languages/julia-repl.min.js
 create mode 100644 assets/lib/highlight/languages/julia.min.js
 create mode 100644 assets/lib/highlight/languages/kotlin.min.js
 create mode 100644 assets/lib/highlight/languages/lasso.min.js
 create mode 100644 assets/lib/highlight/languages/latex.min.js
 create mode 100644 assets/lib/highlight/languages/ldif.min.js
 create mode 100644 assets/lib/highlight/languages/leaf.min.js
 create mode 100644 assets/lib/highlight/languages/less.min.js
 create mode 100644 assets/lib/highlight/languages/lisp.min.js
 create mode 100644 assets/lib/highlight/languages/livecodeserver.min.js
 create mode 100644 assets/lib/highlight/languages/livescript.min.js
 create mode 100644 assets/lib/highlight/languages/llvm.min.js
 create mode 100644 assets/lib/highlight/languages/lsl.min.js
 create mode 100644 assets/lib/highlight/languages/lua.min.js
 create mode 100644 assets/lib/highlight/languages/makefile.min.js
 create mode 100644 assets/lib/highlight/languages/markdown.min.js
 create mode 100644 assets/lib/highlight/languages/mathematica.min.js
 create mode 100644 assets/lib/highlight/languages/matlab.min.js
 create mode 100644 assets/lib/highlight/languages/maxima.min.js
 create mode 100644 assets/lib/highlight/languages/mel.min.js
 create mode 100644 assets/lib/highlight/languages/mercury.min.js
 create mode 100644 assets/lib/highlight/languages/mipsasm.min.js
 create mode 100644 assets/lib/highlight/languages/mizar.min.js
 create mode 100644 assets/lib/highlight/languages/mojolicious.min.js
 create mode 100644 assets/lib/highlight/languages/monkey.min.js
 create mode 100644 assets/lib/highlight/languages/moonscript.min.js
 create mode 100644 assets/lib/highlight/languages/n1ql.min.js
 create mode 100644 assets/lib/highlight/languages/nestedtext.min.js
 create mode 100644 assets/lib/highlight/languages/nginx.min.js
 create mode 100644 assets/lib/highlight/languages/nim.min.js
 create mode 100644 assets/lib/highlight/languages/nix.min.js
 create mode 100644 assets/lib/highlight/languages/node-repl.min.js
 create mode 100644 assets/lib/highlight/languages/nsis.min.js
 create mode 100644 assets/lib/highlight/languages/objectivec.min.js
 create mode 100644 assets/lib/highlight/languages/ocaml.min.js
 create mode 100644 assets/lib/highlight/languages/openscad.min.js
 create mode 100644 assets/lib/highlight/languages/oxygene.min.js
 create mode 100644 assets/lib/highlight/languages/parser3.min.js
 create mode 100644 assets/lib/highlight/languages/perl.min.js
 create mode 100644 assets/lib/highlight/languages/pf.min.js
 create mode 100644 assets/lib/highlight/languages/pgsql.min.js
 create mode 100644 assets/lib/highlight/languages/php-template.min.js
 create mode 100644 assets/lib/highlight/languages/php.min.js
 create mode 100644 assets/lib/highlight/languages/plaintext.min.js
 create mode 100644 assets/lib/highlight/languages/pony.min.js
 create mode 100644 assets/lib/highlight/languages/powershell.min.js
 create mode 100644 assets/lib/highlight/languages/processing.min.js
 create mode 100644 assets/lib/highlight/languages/profile.min.js
 create mode 100644 assets/lib/highlight/languages/prolog.min.js
 create mode 100644 assets/lib/highlight/languages/properties.min.js
 create mode 100644 assets/lib/highlight/languages/protobuf.min.js
 create mode 100644 assets/lib/highlight/languages/puppet.min.js
 create mode 100644 assets/lib/highlight/languages/purebasic.min.js
 create mode 100644 assets/lib/highlight/languages/python-repl.min.js
 create mode 100644 assets/lib/highlight/languages/python.min.js
 create mode 100644 assets/lib/highlight/languages/q.min.js
 create mode 100644 assets/lib/highlight/languages/qml.min.js
 create mode 100644 assets/lib/highlight/languages/r.min.js
 create mode 100644 assets/lib/highlight/languages/reasonml.min.js
 create mode 100644 assets/lib/highlight/languages/rib.min.js
 create mode 100644 assets/lib/highlight/languages/roboconf.min.js
 create mode 100644 assets/lib/highlight/languages/routeros.min.js
 create mode 100644 assets/lib/highlight/languages/rsl.min.js
 create mode 100644 assets/lib/highlight/languages/ruby.min.js
 create mode 100644 assets/lib/highlight/languages/ruleslanguage.min.js
 create mode 100644 assets/lib/highlight/languages/rust.min.js
 create mode 100644 assets/lib/highlight/languages/sas.min.js
 create mode 100644 assets/lib/highlight/languages/scala.min.js
 create mode 100644 assets/lib/highlight/languages/scheme.min.js
 create mode 100644 assets/lib/highlight/languages/scilab.min.js
 create mode 100644 assets/lib/highlight/languages/scss.min.js
 create mode 100644 assets/lib/highlight/languages/shell.min.js
 create mode 100644 assets/lib/highlight/languages/smali.min.js
 create mode 100644 assets/lib/highlight/languages/smalltalk.min.js
 create mode 100644 assets/lib/highlight/languages/sml.min.js
 create mode 100644 assets/lib/highlight/languages/sqf.min.js
 create mode 100644 assets/lib/highlight/languages/sql.min.js
 create mode 100644 assets/lib/highlight/languages/stan.min.js
 create mode 100644 assets/lib/highlight/languages/stata.min.js
 create mode 100644 assets/lib/highlight/languages/step21.min.js
 create mode 100644 assets/lib/highlight/languages/stylus.min.js
 create mode 100644 assets/lib/highlight/languages/subunit.min.js
 create mode 100644 assets/lib/highlight/languages/swift.min.js
 create mode 100644 assets/lib/highlight/languages/taggerscript.min.js
 create mode 100644 assets/lib/highlight/languages/tap.min.js
 create mode 100644 assets/lib/highlight/languages/tcl.min.js
 create mode 100644 assets/lib/highlight/languages/thrift.min.js
 create mode 100644 assets/lib/highlight/languages/tp.min.js
 create mode 100644 assets/lib/highlight/languages/twig.min.js
 create mode 100644 assets/lib/highlight/languages/typescript.min.js
 create mode 100644 assets/lib/highlight/languages/vala.min.js
 create mode 100644 assets/lib/highlight/languages/vbnet.min.js
 create mode 100644 assets/lib/highlight/languages/vbscript-html.min.js
 create mode 100644 assets/lib/highlight/languages/vbscript.min.js
 create mode 100644 assets/lib/highlight/languages/verilog.min.js
 create mode 100644 assets/lib/highlight/languages/vhdl.min.js
 create mode 100644 assets/lib/highlight/languages/vim.min.js
 create mode 100644 assets/lib/highlight/languages/wasm.min.js
 create mode 100644 assets/lib/highlight/languages/wren.min.js
 create mode 100644 assets/lib/highlight/languages/x86asm.min.js
 create mode 100644 assets/lib/highlight/languages/xl.min.js
 create mode 100644 assets/lib/highlight/languages/xml.min.js
 create mode 100644 assets/lib/highlight/languages/xquery.min.js
 create mode 100644 assets/lib/highlight/languages/yaml.min.js
 create mode 100644 assets/lib/highlight/languages/zephir.min.js
 create mode 100644 assets/lib/highlight/package.json
 create mode 100644 assets/lib/highlight/styles/a11y-dark.min.css
 create mode 100644 assets/lib/highlight/styles/a11y-light.min.css
 create mode 100644 assets/lib/highlight/styles/agate.min.css
 create mode 100644 assets/lib/highlight/styles/an-old-hope.min.css
 create mode 100644 assets/lib/highlight/styles/androidstudio.min.css
 create mode 100644 assets/lib/highlight/styles/arduino-light.min.css
 create mode 100644 assets/lib/highlight/styles/arta.min.css
 create mode 100644 assets/lib/highlight/styles/ascetic.min.css
 create mode 100644 assets/lib/highlight/styles/atom-one-dark-reasonable.min.css
 create mode 100644 assets/lib/highlight/styles/atom-one-dark.min.css
 create mode 100644 assets/lib/highlight/styles/atom-one-light.min.css
 create mode 100644 assets/lib/highlight/styles/base16/3024.min.css
 create mode 100644 assets/lib/highlight/styles/base16/apathy.min.css
 create mode 100644 assets/lib/highlight/styles/base16/apprentice.min.css
 create mode 100644 assets/lib/highlight/styles/base16/ashes.min.css
 create mode 100644 assets/lib/highlight/styles/base16/atelier-cave-light.min.css
 create mode 100644 assets/lib/highlight/styles/base16/atelier-cave.min.css
 create mode 100644 assets/lib/highlight/styles/base16/atelier-dune-light.min.css
 create mode 100644 assets/lib/highlight/styles/base16/atelier-dune.min.css
 create mode 100644 assets/lib/highlight/styles/base16/atelier-estuary-light.min.css
 create mode 100644 assets/lib/highlight/styles/base16/atelier-estuary.min.css
 create mode 100644 assets/lib/highlight/styles/base16/atelier-forest-light.min.css
 create mode 100644 assets/lib/highlight/styles/base16/atelier-forest.min.css
 create mode 100644 assets/lib/highlight/styles/base16/atelier-heath-light.min.css
 create mode 100644 assets/lib/highlight/styles/base16/atelier-heath.min.css
 create mode 100644 assets/lib/highlight/styles/base16/atelier-lakeside-light.min.css
 create mode 100644 assets/lib/highlight/styles/base16/atelier-lakeside.min.css
 create mode 100644 assets/lib/highlight/styles/base16/atelier-plateau-light.min.css
 create mode 100644 assets/lib/highlight/styles/base16/atelier-plateau.min.css
 create mode 100644 assets/lib/highlight/styles/base16/atelier-savanna-light.min.css
 create mode 100644 assets/lib/highlight/styles/base16/atelier-savanna.min.css
 create mode 100644 assets/lib/highlight/styles/base16/atelier-seaside-light.min.css
 create mode 100644 assets/lib/highlight/styles/base16/atelier-seaside.min.css
 create mode 100644 assets/lib/highlight/styles/base16/atelier-sulphurpool-light.min.css
 create mode 100644 assets/lib/highlight/styles/base16/atelier-sulphurpool.min.css
 create mode 100644 assets/lib/highlight/styles/base16/atlas.min.css
 create mode 100644 assets/lib/highlight/styles/base16/bespin.min.css
 create mode 100644 assets/lib/highlight/styles/base16/black-metal-bathory.min.css
 create mode 100644 assets/lib/highlight/styles/base16/black-metal-burzum.min.css
 create mode 100644 assets/lib/highlight/styles/base16/black-metal-dark-funeral.min.css
 create mode 100644 assets/lib/highlight/styles/base16/black-metal-gorgoroth.min.css
 create mode 100644 assets/lib/highlight/styles/base16/black-metal-immortal.min.css
 create mode 100644 assets/lib/highlight/styles/base16/black-metal-khold.min.css
 create mode 100644 assets/lib/highlight/styles/base16/black-metal-marduk.min.css
 create mode 100644 assets/lib/highlight/styles/base16/black-metal-mayhem.min.css
 create mode 100644 assets/lib/highlight/styles/base16/black-metal-nile.min.css
 create mode 100644 assets/lib/highlight/styles/base16/black-metal-venom.min.css
 create mode 100644 assets/lib/highlight/styles/base16/black-metal.min.css
 create mode 100644 assets/lib/highlight/styles/base16/brewer.min.css
 create mode 100644 assets/lib/highlight/styles/base16/bright.min.css
 create mode 100644 assets/lib/highlight/styles/base16/brogrammer.min.css
 create mode 100644 assets/lib/highlight/styles/base16/brush-trees-dark.min.css
 create mode 100644 assets/lib/highlight/styles/base16/brush-trees.min.css
 create mode 100644 assets/lib/highlight/styles/base16/chalk.min.css
 create mode 100644 assets/lib/highlight/styles/base16/circus.min.css
 create mode 100644 assets/lib/highlight/styles/base16/classic-dark.min.css
 create mode 100644 assets/lib/highlight/styles/base16/classic-light.min.css
 create mode 100644 assets/lib/highlight/styles/base16/codeschool.min.css
 create mode 100644 assets/lib/highlight/styles/base16/colors.min.css
 create mode 100644 assets/lib/highlight/styles/base16/cupcake.min.css
 create mode 100644 assets/lib/highlight/styles/base16/cupertino.min.css
 create mode 100644 assets/lib/highlight/styles/base16/danqing.min.css
 create mode 100644 assets/lib/highlight/styles/base16/darcula.min.css
 create mode 100644 assets/lib/highlight/styles/base16/dark-violet.min.css
 create mode 100644 assets/lib/highlight/styles/base16/darkmoss.min.css
 create mode 100644 assets/lib/highlight/styles/base16/darktooth.min.css
 create mode 100644 assets/lib/highlight/styles/base16/decaf.min.css
 create mode 100644 assets/lib/highlight/styles/base16/default-dark.min.css
 create mode 100644 assets/lib/highlight/styles/base16/default-light.min.css
 create mode 100644 assets/lib/highlight/styles/base16/dirtysea.min.css
 create mode 100644 assets/lib/highlight/styles/base16/dracula.min.css
 create mode 100644 assets/lib/highlight/styles/base16/edge-dark.min.css
 create mode 100644 assets/lib/highlight/styles/base16/edge-light.min.css
 create mode 100644 assets/lib/highlight/styles/base16/eighties.min.css
 create mode 100644 assets/lib/highlight/styles/base16/embers.min.css
 create mode 100644 assets/lib/highlight/styles/base16/equilibrium-dark.min.css
 create mode 100644 assets/lib/highlight/styles/base16/equilibrium-gray-dark.min.css
 create mode 100644 assets/lib/highlight/styles/base16/equilibrium-gray-light.min.css
 create mode 100644 assets/lib/highlight/styles/base16/equilibrium-light.min.css
 create mode 100644 assets/lib/highlight/styles/base16/espresso.min.css
 create mode 100644 assets/lib/highlight/styles/base16/eva-dim.min.css
 create mode 100644 assets/lib/highlight/styles/base16/eva.min.css
 create mode 100644 assets/lib/highlight/styles/base16/flat.min.css
 create mode 100644 assets/lib/highlight/styles/base16/framer.min.css
 create mode 100644 assets/lib/highlight/styles/base16/fruit-soda.min.css
 create mode 100644 assets/lib/highlight/styles/base16/gigavolt.min.css
 create mode 100644 assets/lib/highlight/styles/base16/github.min.css
 create mode 100644 assets/lib/highlight/styles/base16/google-dark.min.css
 create mode 100644 assets/lib/highlight/styles/base16/google-light.min.css
 create mode 100644 assets/lib/highlight/styles/base16/grayscale-dark.min.css
 create mode 100644 assets/lib/highlight/styles/base16/grayscale-light.min.css
 create mode 100644 assets/lib/highlight/styles/base16/green-screen.min.css
 create mode 100644 assets/lib/highlight/styles/base16/gruvbox-dark-hard.min.css
 create mode 100644 assets/lib/highlight/styles/base16/gruvbox-dark-medium.min.css
 create mode 100644 assets/lib/highlight/styles/base16/gruvbox-dark-pale.min.css
 create mode 100644 assets/lib/highlight/styles/base16/gruvbox-dark-soft.min.css
 create mode 100644 assets/lib/highlight/styles/base16/gruvbox-light-hard.min.css
 create mode 100644 assets/lib/highlight/styles/base16/gruvbox-light-medium.min.css
 create mode 100644 assets/lib/highlight/styles/base16/gruvbox-light-soft.min.css
 create mode 100644 assets/lib/highlight/styles/base16/hardcore.min.css
 create mode 100644 assets/lib/highlight/styles/base16/harmonic16-dark.min.css
 create mode 100644 assets/lib/highlight/styles/base16/harmonic16-light.min.css
 create mode 100644 assets/lib/highlight/styles/base16/heetch-dark.min.css
 create mode 100644 assets/lib/highlight/styles/base16/heetch-light.min.css
 create mode 100644 assets/lib/highlight/styles/base16/helios.min.css
 create mode 100644 assets/lib/highlight/styles/base16/hopscotch.min.css
 create mode 100644 assets/lib/highlight/styles/base16/horizon-dark.min.css
 create mode 100644 assets/lib/highlight/styles/base16/horizon-light.min.css
 create mode 100644 assets/lib/highlight/styles/base16/humanoid-dark.min.css
 create mode 100644 assets/lib/highlight/styles/base16/humanoid-light.min.css
 create mode 100644 assets/lib/highlight/styles/base16/ia-dark.min.css
 create mode 100644 assets/lib/highlight/styles/base16/ia-light.min.css
 create mode 100644 assets/lib/highlight/styles/base16/icy-dark.min.css
 create mode 100644 assets/lib/highlight/styles/base16/ir-black.min.css
 create mode 100644 assets/lib/highlight/styles/base16/isotope.min.css
 create mode 100644 assets/lib/highlight/styles/base16/kimber.min.css
 create mode 100644 assets/lib/highlight/styles/base16/london-tube.min.css
 create mode 100644 assets/lib/highlight/styles/base16/macintosh.min.css
 create mode 100644 assets/lib/highlight/styles/base16/marrakesh.min.css
 create mode 100644 assets/lib/highlight/styles/base16/materia.min.css
 create mode 100644 assets/lib/highlight/styles/base16/material-darker.min.css
 create mode 100644 assets/lib/highlight/styles/base16/material-lighter.min.css
 create mode 100644 assets/lib/highlight/styles/base16/material-palenight.min.css
 create mode 100644 assets/lib/highlight/styles/base16/material-vivid.min.css
 create mode 100644 assets/lib/highlight/styles/base16/material.min.css
 create mode 100644 assets/lib/highlight/styles/base16/mellow-purple.min.css
 create mode 100644 assets/lib/highlight/styles/base16/mexico-light.min.css
 create mode 100644 assets/lib/highlight/styles/base16/mocha.min.css
 create mode 100644 assets/lib/highlight/styles/base16/monokai.min.css
 create mode 100644 assets/lib/highlight/styles/base16/nebula.min.css
 create mode 100644 assets/lib/highlight/styles/base16/nord.min.css
 create mode 100644 assets/lib/highlight/styles/base16/nova.min.css
 create mode 100644 assets/lib/highlight/styles/base16/ocean.min.css
 create mode 100644 assets/lib/highlight/styles/base16/oceanicnext.min.css
 create mode 100644 assets/lib/highlight/styles/base16/one-light.min.css
 create mode 100644 assets/lib/highlight/styles/base16/onedark.min.css
 create mode 100644 assets/lib/highlight/styles/base16/outrun-dark.min.css
 create mode 100644 assets/lib/highlight/styles/base16/papercolor-dark.min.css
 create mode 100644 assets/lib/highlight/styles/base16/papercolor-light.min.css
 create mode 100644 assets/lib/highlight/styles/base16/paraiso.min.css
 create mode 100644 assets/lib/highlight/styles/base16/pasque.min.css
 create mode 100644 assets/lib/highlight/styles/base16/phd.min.css
 create mode 100644 assets/lib/highlight/styles/base16/pico.min.css
 create mode 100644 assets/lib/highlight/styles/base16/pop.min.css
 create mode 100644 assets/lib/highlight/styles/base16/porple.min.css
 create mode 100644 assets/lib/highlight/styles/base16/qualia.min.css
 create mode 100644 assets/lib/highlight/styles/base16/railscasts.min.css
 create mode 100644 assets/lib/highlight/styles/base16/rebecca.min.css
 create mode 100644 assets/lib/highlight/styles/base16/ros-pine-dawn.min.css
 create mode 100644 assets/lib/highlight/styles/base16/ros-pine-moon.min.css
 create mode 100644 assets/lib/highlight/styles/base16/ros-pine.min.css
 create mode 100644 assets/lib/highlight/styles/base16/sagelight.min.css
 create mode 100644 assets/lib/highlight/styles/base16/sandcastle.min.css
 create mode 100644 assets/lib/highlight/styles/base16/seti-ui.min.css
 create mode 100644 assets/lib/highlight/styles/base16/shapeshifter.min.css
 create mode 100644 assets/lib/highlight/styles/base16/silk-dark.min.css
 create mode 100644 assets/lib/highlight/styles/base16/silk-light.min.css
 create mode 100644 assets/lib/highlight/styles/base16/snazzy.min.css
 create mode 100644 assets/lib/highlight/styles/base16/solar-flare-light.min.css
 create mode 100644 assets/lib/highlight/styles/base16/solar-flare.min.css
 create mode 100644 assets/lib/highlight/styles/base16/solarized-dark.min.css
 create mode 100644 assets/lib/highlight/styles/base16/solarized-light.min.css
 create mode 100644 assets/lib/highlight/styles/base16/spacemacs.min.css
 create mode 100644 assets/lib/highlight/styles/base16/summercamp.min.css
 create mode 100644 assets/lib/highlight/styles/base16/summerfruit-dark.min.css
 create mode 100644 assets/lib/highlight/styles/base16/summerfruit-light.min.css
 create mode 100644 assets/lib/highlight/styles/base16/synth-midnight-terminal-dark.min.css
 create mode 100644 assets/lib/highlight/styles/base16/synth-midnight-terminal-light.min.css
 create mode 100644 assets/lib/highlight/styles/base16/tango.min.css
 create mode 100644 assets/lib/highlight/styles/base16/tender.min.css
 create mode 100644 assets/lib/highlight/styles/base16/tomorrow-night.min.css
 create mode 100644 assets/lib/highlight/styles/base16/tomorrow.min.css
 create mode 100644 assets/lib/highlight/styles/base16/twilight.min.css
 create mode 100644 assets/lib/highlight/styles/base16/unikitty-dark.min.css
 create mode 100644 assets/lib/highlight/styles/base16/unikitty-light.min.css
 create mode 100644 assets/lib/highlight/styles/base16/vulcan.min.css
 create mode 100644 assets/lib/highlight/styles/base16/windows-10-light.min.css
 create mode 100644 assets/lib/highlight/styles/base16/windows-10.min.css
 create mode 100644 assets/lib/highlight/styles/base16/windows-95-light.min.css
 create mode 100644 assets/lib/highlight/styles/base16/windows-95.min.css
 create mode 100644 assets/lib/highlight/styles/base16/windows-high-contrast-light.min.css
 create mode 100644 assets/lib/highlight/styles/base16/windows-high-contrast.min.css
 create mode 100644 assets/lib/highlight/styles/base16/windows-nt-light.min.css
 create mode 100644 assets/lib/highlight/styles/base16/windows-nt.min.css
 create mode 100644 assets/lib/highlight/styles/base16/woodland.min.css
 create mode 100644 assets/lib/highlight/styles/base16/xcode-dusk.min.css
 create mode 100644 assets/lib/highlight/styles/base16/zenburn.min.css
 create mode 100644 assets/lib/highlight/styles/brown-paper.min.css
 create mode 100644 assets/lib/highlight/styles/brown-papersq.png
 create mode 100644 assets/lib/highlight/styles/codepen-embed.min.css
 create mode 100644 assets/lib/highlight/styles/color-brewer.min.css
 create mode 100644 assets/lib/highlight/styles/dark.min.css
 create mode 100644 assets/lib/highlight/styles/default.min.css
 create mode 100644 assets/lib/highlight/styles/devibeans.min.css
 create mode 100644 assets/lib/highlight/styles/docco.min.css
 create mode 100644 assets/lib/highlight/styles/far.min.css
 create mode 100644 assets/lib/highlight/styles/felipec.min.css
 create mode 100644 assets/lib/highlight/styles/foundation.min.css
 create mode 100644 assets/lib/highlight/styles/github-dark-dimmed.min.css
 create mode 100644 assets/lib/highlight/styles/github-dark.min.css
 create mode 100644 assets/lib/highlight/styles/github.min.css
 create mode 100644 assets/lib/highlight/styles/gml.min.css
 create mode 100644 assets/lib/highlight/styles/googlecode.min.css
 create mode 100644 assets/lib/highlight/styles/gradient-dark.min.css
 create mode 100644 assets/lib/highlight/styles/gradient-light.min.css
 create mode 100644 assets/lib/highlight/styles/grayscale.min.css
 create mode 100644 assets/lib/highlight/styles/hybrid.min.css
 create mode 100644 assets/lib/highlight/styles/idea.min.css
 create mode 100644 assets/lib/highlight/styles/intellij-light.min.css
 create mode 100644 assets/lib/highlight/styles/ir-black.min.css
 create mode 100644 assets/lib/highlight/styles/isbl-editor-dark.min.css
 create mode 100644 assets/lib/highlight/styles/isbl-editor-light.min.css
 create mode 100644 assets/lib/highlight/styles/kimbie-dark.min.css
 create mode 100644 assets/lib/highlight/styles/kimbie-light.min.css
 create mode 100644 assets/lib/highlight/styles/lightfair.min.css
 create mode 100644 assets/lib/highlight/styles/lioshi.min.css
 create mode 100644 assets/lib/highlight/styles/magula.min.css
 create mode 100644 assets/lib/highlight/styles/mono-blue.min.css
 create mode 100644 assets/lib/highlight/styles/monokai-sublime.min.css
 create mode 100644 assets/lib/highlight/styles/monokai.min.css
 create mode 100644 assets/lib/highlight/styles/night-owl.min.css
 create mode 100644 assets/lib/highlight/styles/nnfx-dark.min.css
 create mode 100644 assets/lib/highlight/styles/nnfx-light.min.css
 create mode 100644 assets/lib/highlight/styles/nord.min.css
 create mode 100644 assets/lib/highlight/styles/obsidian.min.css
 create mode 100644 assets/lib/highlight/styles/panda-syntax-dark.min.css
 create mode 100644 assets/lib/highlight/styles/panda-syntax-light.min.css
 create mode 100644 assets/lib/highlight/styles/paraiso-dark.min.css
 create mode 100644 assets/lib/highlight/styles/paraiso-light.min.css
 create mode 100644 assets/lib/highlight/styles/pojoaque.jpg
 create mode 100644 assets/lib/highlight/styles/pojoaque.min.css
 create mode 100644 assets/lib/highlight/styles/purebasic.min.css
 create mode 100644 assets/lib/highlight/styles/qtcreator-dark.min.css
 create mode 100644 assets/lib/highlight/styles/qtcreator-light.min.css
 create mode 100644 assets/lib/highlight/styles/rainbow.min.css
 create mode 100644 assets/lib/highlight/styles/routeros.min.css
 create mode 100644 assets/lib/highlight/styles/school-book.min.css
 create mode 100644 assets/lib/highlight/styles/shades-of-purple.min.css
 create mode 100644 assets/lib/highlight/styles/srcery.min.css
 create mode 100644 assets/lib/highlight/styles/stackoverflow-dark.min.css
 create mode 100644 assets/lib/highlight/styles/stackoverflow-light.min.css
 create mode 100644 assets/lib/highlight/styles/sunburst.min.css
 create mode 100644 assets/lib/highlight/styles/tokyo-night-dark.min.css
 create mode 100644 assets/lib/highlight/styles/tokyo-night-light.min.css
 create mode 100644 assets/lib/highlight/styles/tomorrow-night-blue.min.css
 create mode 100644 assets/lib/highlight/styles/tomorrow-night-bright.min.css
 create mode 100644 assets/lib/highlight/styles/vs.min.css
 create mode 100644 assets/lib/highlight/styles/vs2015.min.css
 create mode 100644 assets/lib/highlight/styles/xcode.min.css
 create mode 100644 assets/lib/highlight/styles/xt256.min.css
 create mode 100644 site/snippets/--inspector--BKP.php
 create mode 100644 site/snippets/inspector-code-elements.php
 create mode 100644 site/snippets/inspector-code-sources.php
EOT;
$elementsTabContent = Html::encode($elements);

echo $elementsTabContent;